# This is a basic workflow
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions


name: CI-pipeline
#env:
#  APP_NAME    : "converter"
#  PACKAGE_NAME: "converter_app_${{ github.sha }}"

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches-ignore: [ "main", "dev" ]

jobs:
  test_codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install flake and check code-style
        run: |
          python -m pip install flake8
          flake8 .
  test_security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check security
        run: |
          python -m pip install bandit
          bandit -r .
          

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test
        run: |
          date -R >> artifact.txt
          python -m unittest >> artifact.txt
