# This is a basic workflow
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions


name: CI-pipeline
env:
  APP_NAME    : "converter"
  PACKAGE_NAME: "converter_app_${{ github.sha }}"


# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches-ignore: [ "main", "dev" ]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: GIT clone repository
        uses: actions/checkout@v3

      - name: Install pylint
        run: |
          pip install pylint
          pylint temp_convertor\main.py

      - name: Check environment
        run: |
          echo "Application name is: ${{ env.APP_NAME }}" >> artifact.txt
          echo "Application version is: $ {{ env.PACKAGE_NAME }}" >> artifact.txt

      - name: Run test
        run: |
          date -R >> artifact.txt
          python -m unittest >> artifact.txt

#    strategy:
#      max-parallel: 2
#      matrix:
#        python-version: [3.6, 3.8]
#    env:
#      VAR1: "123"
#      VAR2: "Job value in Job"


#  tests:
#    - name: Test with unittest
#      needs:
#      run:
#          python -m unittest


